FROM alpine

COPY entrypoint-proxy /entrypoint

RUN adduser -D -u 54000 radio && \
        apk update && \
        apk add git gcc musl-dev pypy pypy-dev && \
        cd /opt && \
        git clone https://github.com/hacknix/freedmr && \
        cd /opt/freedmr && \
        pypy3 -m pip install --no-cache-dir -r requirements.txt && \
        apk del git gcc musl-dev pypy-dev && \
        chown -R radio: /opt/freedmr

USER radio

ENTRYPOINT [ "/entrypoint" ]
