version: '2.1'
services:
    freedmr:
        container_name: freedmr
        volumes:
            - '/etc/freedmr/freedmr.cfg:/opt/freedmr/freedmr.cfg'
            - '/var/log/freedmr/freedmr.log:/opt/freedmr/freedmr.log'
            - '/etc/freedmr/rules.py:/opt/freedmr/rules.py'
            #Write JSON files outside of container
            - '/etc/freedmr/json/talkgroup_ids.json:/opt/freedmr/talkgroup_ids.json'
            - '/etc/freedmr/json/subscriber_ids.json:/opt/freedmr/subscriber_ids.json'
            - '/etc/freedmr/json/peer_ids.json:/opt/freedmr/peer_ids.json'
        ports:
            - '62031:62031/udp'
            - '62044-62049:62044-62049/udp'
        image: 'hacknix/freedmr:latest'
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.10
        read_only: "true"

    freedmrmon:
        container_name: freedmrmon
        depends_on:
            - freedmr
        volumes:
            #This should be kept to a manageable size from
            #cron or logrotate outisde of the container.
            - '/var/log/FreeDMRmonitor/lastheard.log:/opt/FreeDMRmonitor/log/lastheard.log'
            - '/var/log/FreeDMRmonitor/hbmon.log:/opt/FreeDMRmonitor/log/hbmon.log'
            #Write JSON files outside of container
            - '/etc/freedmr/json/talkgroup_ids.json:/opt/FreeDMRmonitor/talkgroup_ids.json'
            - '/etc/freedmr/json/subscriber_ids.json:/opt/FreeDMRmonitor/subscriber_ids.json'
            - '/etc/freedmr/json/peer_ids.json:/opt/FreeDMRmonitor/peer_ids.json'

        #Override config file
        #    - '/etc/freedmr/config.py:/opt/FreeDMRmonitor/config.py'
        ports:
            - '9000:9000/tcp'
        image: 'hacknix/freedmrmonitor:latest'
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.20
     
    freedmrmonpache:
        container_name: freedmrmonapache
        depends_on:
             - freedmrmon
        #Use to override html files
        #And images
        #volumes:
        #    - '/var/www/html/:/var/www/html/'
        #    - '/var/www/html/images/:/var/www/html/images/'
        ports:
            - '80:80/tcp'
        image: hacknix/freedmrmonitor-apache:latest
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.30

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
