version: '2.1'
services:
    freedmr:
        container_name: freedmr
        volumes:
            - '/etc/freedmr/freedmr.cfg:/opt/freedmr/freedmr.cfg'
            - '/var/log/freedmr/freedmr.log:/opt/freedmr/freedmr.log'
            - '/etc/freedmr/rules.py:/opt/freedmr/rules.py'
#Uncomment these are create appropriate path and files if you want to make downloaded
#JSON files available outside of the container
#            - '/etc/freedmr/json/talkgroup_ids.json:/opt/freedmr/talkgroup_ids.json'
#            - '/etc/freedmr/json/subscriber_ids.json:/opt/freedmr/subscriber_ids.json'
#            - '/etc/freedmr/json/peer_ids.json:/opt/freedmr/peer_ids.json'
        ports:
            - '62031:62031/udp'
            - '62045-62049:62045-62049/udp'
            - '4321:4321/tcp'
        image: 'hacknix/freedmr:development-latest'
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.10
             ipv6_address: fd2a:70b6:9f54:29b6::10

    ipv6nat:
        container_name: ipv6nat
        image: 'robbertkl/ipv6nat'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '/lib/modules:/lib/modules:ro'
        privileged: "true"
        network_mode: "host"
        restart: "unless-stopped"

networks:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: fd2a:70b6:9f54:29b6::/64
        gateway: fd2a:70b6:9f54:29b6::1
