###############################################################################  
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
#
###############################################################################

version: '2.4'
services:

    adn-server:
        container_name: adn-server
        cpu_shares: 1024
        mem_reservation: 600m
        volumes:
            - '/etc/ADN-Systems/adn.cfg:/opt/ADN-DMR-Peer-Server/config/adn.cfg'
        ports:
            - '62031:62031/udp'
            #Change the below to inlude ports used for your OBP(s)
            - '62041:62041/udp'
            - '8000:8000'
        image: 'registry.gitlab.com/hp3icc/fdmr/adn-server-single:latest'
        restart: "unless-stopped"
        logging:
          driver: none
        networks:
          - bridge
        #Control parameters inside container
        environment:
            #IPV6 support 
            - FDPROXY_IPV6=0
            #Display connection stats in log
            - FDPROXY_STATS=1
            #Display conneting client info in log
            - FDPROXY_CLIENTINFO=1
            #Debug HBP session in log (lots of data!!)
            - FDPROXY_DEBUG=0
            #Override proxy external port
            #- FDPROXY_LISTENPORT=62031


    adn-dashboard:
        container_name: adn-dashboard
        cpu_shares: 512
        volumes:
             - '/etc/ADN-Systems/fdmr-mon.cfg:/opt/FDMR-Monitor/fdmr-mon.cfg'
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
            - '9000:9000'
        image: 'registry.gitlab.com/hp3icc/fdmr/adn-mon2-single:latest'
        restart: "unless-stopped"
          #Set USE_SSL = to True to enable TLS support
          #you'll need to actually generate the certtificates too
          #using these commands when the container is running:

          #docker exec -it adn-dashboard gencert.sh <admin email> <server FQDN>
          #docker-compose restart adn-dashboard

          #This only needs to be done once - unless the files in the volumes above are deleted.

          #The container will handle renewing the certificates every 60 days.  

          #Note -the gencert.sh script only works when the webserver is available on the default port 80  
          #If it's on non-standard ports, you'll need to request the certificates manually. 
        logging:
          driver: none
        networks:
          - bridge

networks:
  bridge:
    driver: bridge

