FROM alpine

COPY entrypoint-proxy /entrypoint

RUN adduser -D -u 54000 radio && \
	echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
        apk update && \
        apk add git gcc musl-dev curl && \
        cd /opt && \
	curl https://downloads.python.org/pypy/pypy3.7-v7.3.5-linux64.tar.bz2 -o pypy.tar.bz2 && \
	mkdir pypy && \
	cd pypy && \
	tar jxvf ../pypy.tar.bz2 --strip-components=1 && \
	ln  /bin/pypy /opt/pypy/bin/pypy && \
	cd .. &&\
        git clone https://github.com/hacknix/freedmr && \
        cd /opt/freedmr && \
	pypy -m ensurepip && \
        pypy -m pip install --no-cache-dir -r requirements.txt && \
        apk del git gcc musl-dev pypy-dev && \
        chown -R radio: /opt/freedmr

USER radio

ENTRYPOINT [ "/entrypoint" ]
