FROM debian:bullseye-slim

COPY entrypoint-proxy /entrypoint

RUN useradd -u 54000 radio && \
        apt-get update && \
        apt-get -y  install git gcc musl-dev pypy3 pypy3-dev && \
	cd /opt && \
        git clone https://github.com/hacknix/freedmr && \
        cd /opt/freedmr && \
	pypy3 -m ensurepip && \
        pypy3 -m pip install --no-cache-dir -r requirements.txt && \
        apt-get -y remove gcc musl-dev pypy-dev && \
	apt-get -y autoremove && \
	apt-get -y purge && \
	rm -rvf /var/cache/apt/archives/* && \
        chown -R radio: /opt/freedmr

USER radio

ENTRYPOINT [ "/entrypoint" ]
